# Generated by Django 4.2.3 on 2023-07-11 10:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pet_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="petowner",
            name="pet_owner_experience",
            field=models.IntegerField(default=0),
        ),
    ]
