# Generated by Django 4.2.3 on 2023-07-11 11:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pet_app", "0002_alter_petowner_pet_owner_experience"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="petowner",
            options={"verbose_name": "pet owner", "verbose_name_plural": "pet owners"},
        ),
        migrations.AlterField(
            model_name="pet",
            name="breed",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
